### ISSUE TITLE
Does it need to add additional dependencies for tachyon-client?

### ISSUE THREAD

**Issue by gewanbo** [amplab/tachyon#1203]
I use Tachyon as a client for my application. I add these dependencies section below in my maven project.

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <scala.version>2.10.4</scala.version>
        <akka.version>2.3.9</akka.version>
        <org.slf4j.version>1.7.5</org.slf4j.version>
        <org.tachyonproject.version>0.7.0</org.tachyonproject.version>
        <file_encoding>UTF-8</file_encoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.tachyonproject</groupId>
            <artifactId>tachyon-servers</artifactId>
            <version>${org.tachyonproject.version}</version>
        </dependency>
        <dependency>
            <groupId>org.tachyonproject</groupId>
            <artifactId>tachyon-client</artifactId>
            <version>${org.tachyonproject.version}</version>
        </dependency>
        <dependency>
            <groupId>org.tachyonproject</groupId>
            <artifactId>tachyon-common</artifactId>
            <version>${org.tachyonproject.version}</version>
        </dependency>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scala.version}</version>
        </dependency>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-actors</artifactId>
            <version>${scala.version}</version>
        </dependency>
    </dependencies>

When I run my application on a worker machine. It throws exception:

    15/07/31 14:23:35 INFO : Opening stream from underlayer fs: /local/server/tachyon-0.7.0/underFSStorage/tmp/tachyon/data/5
    15/07/31 14:23:35 WARN : No Under File System Factory implementation supports the path /local/server/tachyon-0.7.0/underFSStorage/tmp/tachyon/data/5
    Exception in thread "main" java.lang.IllegalArgumentException: No Under File System Factory found for: /local/server/tachyon-0.7.0/underFSStorage/tmp/tachyon/data/5
        at tachyon.underfs.UnderFileSystemRegistry.create(UnderFileSystemRegistry.java:109)
        at tachyon.underfs.UnderFileSystem.get(UnderFileSystem.java:99)
        at tachyon.client.RemoteBlockInStream.setupStreamFromUnderFs(RemoteBlockInStream.java:347)
        at tachyon.client.RemoteBlockInStream.read(RemoteBlockInStream.java:237)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:154)
        at java.io.BufferedReader.read(BufferedReader.java:175)
        at scala.io.BufferedSource$$anonfun$iter$1$$anonfun$apply$mcI$sp$1.apply$mcI$sp(BufferedSource.scala:38)
        at scala.io.Codec.wrap(Codec.scala:68)
        at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38)
        at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
        at scala.collection.Iterator$$anon$17.hasNext(Iterator.scala:511)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.io.Source.hasNext(Source.scala:226)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.io.Source.foreach(Source.scala:178)
        at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:320)
        at scala.io.Source.addString(Source.scala:178)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:286)
        at scala.io.Source.mkString(Source.scala:178)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:288)
        at scala.io.Source.mkString(Source.scala:178)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:290)
        at scala.io.Source.mkString(Source.scala:178)
        at org.test.Test$.main(Test.scala:43)
        at org.test.Test.main(Test.scala)

If use the jar file "tachyon-assemblies-0.7.0-jar-with-dependencies.jar" from the Tachyon source package, It can runs well. So I guess, did I need to add additional dependencies for tachyon client?

**Comment by apc999** [comment]
@gewanbo to post questions in user forum: https://groups.google.com/forum/?fromgroups#!forum/tachyon-users, so more users can see and help you in this problem, and later users can also benefit from the discussion :)

**Comment by gewanbo** [comment]
Moved to mail list.
