### ISSUE TITLE
Not able to run wordcount with Tachyon

### ISSUE THREAD

**Issue by studhadoop** [amplab/tachyon#2427]
I am trying to run Hadoop Wordcount on Tachyon. I followed this link. But once I run wordcount Jar with below command

hadoop jar HadoopWordCount-0.0.1-SNAPSHOT-jar-with-dependencies.jar edu.WordCount -libjars tachyon-client-0.7.1-jar-with-dependencies.jar tachyon://tachyon_ip:19998/wordcountsample/word2.txtaa /OUT/wcTachyon

Error: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class tachyon.hadoop.TFS not found
    at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2112)
    at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2578)
    at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2591)
    at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)
    at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2630)
    at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2612)
    at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
    at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)

Can u pls let me know what is the issue.
I have set the properties in core-site and hdfs-site.

**Comment by haoyuan** [comment]
Please file and track issues in JIRA https://tachyon.atlassian.net/browse/TACHYON/ , and post questions in user forum: https://groups.google.com/forum/?fromgroups#!forum/tachyon-users

Thanks.
